fun main() {
    print("В"); Thread.sleep(200)
    print("а"); Thread.sleep(200)
    print("с"); Thread.sleep(200)
    print(" "); Thread.sleep(200)
    print("п"); Thread.sleep(200)
    print("р"); Thread.sleep(200)
    print("и"); Thread.sleep(200)
    print("в"); Thread.sleep(200)
    print("е"); Thread.sleep(200)
    print("т"); Thread.sleep(200)
    print("с"); Thread.sleep(200)
    print("т"); Thread.sleep(200)
    print("в"); Thread.sleep(200)
    print("у"); Thread.sleep(200)
    print("е"); Thread.sleep(200)
    print("т"); Thread.sleep(200)
    print(" "); Thread.sleep(200)
    print("л"); Thread.sleep(200)
    print("о"); Thread.sleep(200)
    print("х"); Thread.sleep(200)
    print("о"); Thread.sleep(200)
    print("т"); Thread.sleep(200)
    print("р"); Thread.sleep(200)
    print("о"); Thread.sleep(200)
    print("н"); Thread.sleep(200)
    print("."); Thread.sleep(200)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("О");Thread.sleep(300)
    print("й");Thread.sleep(300)
    print("!");Thread.sleep(300)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
    print("\b");Thread.sleep(150)
}





//print("Вас приветствует лохотрон.\n"); Thread.sleep(3000)
//print("Ой...\n"); Thread.sleep(600)
//print("Точнее...\n"); Thread.sleep(300)
//print("Чесный бар-казино.\n"); Thread.sleep(600)
//println("По моим подсчётам")